zakbot.replies.enabled=true

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000

spring.jpa.open-in-view=false

server.tomcat.threads.max=10
server.tomcat.threads.min-spare=2

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/javascript,application/json

spring.web.resources.cache.cachecontrol.max-age=1d