INSERT INTO public.phrase (content, usages, type, source) VALUES ('I think our human eyeballs - our living eyeballs - see this town as it is now.', 7, 3, 'Apache Junction');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, you go in first.', 10, 0, 'Lost Souls of the Berkeley');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There''s a blinding pain in my back; super, super piercing.', 7, 3, 'Lost Souls of the Berkeley');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m feeling an uncontrollable rage coming over me.', 14, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Sometimes Aaron''s face is scarier than anything we see or capture on our cameras.', 10, 0, 'Mayhem in Marquette (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('C R E D I B I L I T Y', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('That is a crystal-clear, intelligent response.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('If there''s something to know about our good friend Aaron Goodwin, is he''s the clumsiest guy that we know.', 10, 0, 'Chaos in Emmaus (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There has to be a portal over here!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Bro, are you serious?!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Dude, are you kidding me?!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('A witch doused Aaron in goat''s blood during a pagan ritual. He wasn''t the same after that ceremony.', 10, 0, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('DUDE!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Bill Chappell can''t give us an explanation.', 7, 3, 'The show''s intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There''s an ice-cold mass right here, FEEL!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I just felt an unnatural shift in the energy.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, I want you to lay down on the futon.', 10, 0, 'Crisis in Long Beach (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('OMG DUDE!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('As the house has been abandoned, it''s very possible that a cat did jump up on the bed and urinate exactly where Aaron''s head is.', 10, 0, 'Mountain Oaks Mayhem');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('DUDE WHAT WAS THAT?!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Do you wanna tickle my big ol'' long toes?', 6, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I believe that a spirit is strongly attracted to Aaron, because he is showing the most fear.', 10, 0, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Much to Aaron''s delight, I am locked down in the dark.', 10, 0, 'Battle of Los Angeles');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Guys, I''m being affected!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('The hearing in the left side of my face went numb.', 6, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('The mob can turn on you on a [bleep] dime.', 7, 3, 'The Riviera Hotel');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There is a strange and powerful confusion that is penetrating all of us.', 7, 3, 'Los Feliz Murder House Part 1');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You want to pick on someone? Pick on me!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('NEVER eat a Crockpot of beans before a paranormal investigation.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel an overwhelming sense of sadness.', 14, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Don''t ever lunge for a donkey''s ass.', 7, 3, 'Yorktown Hospital');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron now returns, and I begin forcefully pushing him into the room with the spirit board.', 10, 0, 'Mountain Oaks Mayhem');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, go lock yourself in the basement!', 10, 0, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('A light orb just shot into {author}''s arm!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Did someone just scratch me?!', 6, 3, 'The show''s old intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Did you know that "situation" is correctly pronounced "sid-ju-ation"?', 9, 5, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Dude, is it getting cold in here?!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, get in the bed with me man, and we can feel the vibrations together.', 10, 0, 'S09E02');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m feeling inexplicably uneasy, as if the building is aware of our presence.', 14, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This evidence is extremely compelling.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('BRO!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I can feel you, we can feel you, my friend Aaron and I.', 7, 3, 'Territorial Enterprise');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It''s icy cold all around me!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I want Aaron to go into this crawlspace by himself.', 10, 0, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('SHHHHHH! Be quiet! Listen!', 6, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is like some type of dark tentacle of some type of spiritual creature, entity. And this was in your bedroom.', 7, 3, 'Emergency in Elk Grove');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Capturing ground-breaking proof... [of how to pronounce "mercury".](https://www.youtube.com/watch?v=mjhBo0u6-wU)', 2, 4, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There are things in this world we will never fully understand... [like how to pronounce "mercury".](https://www.youtube.com/watch?v=mjhBo0u6-wU)', 2, 4, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Let''s just call this a demon spiderweb.', 7, 3, 'Letchworth Village');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('NO WAY BRO!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel like there''s something here that wants me to connect with it.', 14, 2, 'Petrified in Pahrump');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('IT''S CLIMBING UP YOU!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It''s giving me rage!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Look at Aaron''s arm hair!', 11, 0, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I can feel the fear all around me.', 14, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel physically drained at the moment; the spirits are feeding off my energy.', 14, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I own some odd fellows'' human skeletons; I own a mummified head.', 7, 3, 'Territorial Enterprise');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I have anxiety too. I feel it through this connection.', 7, 3, 'Mayhem in Marquette (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m suddenly feeling angry and aggressive...', 14, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, lay in the bed, would you?', 11, 0, 'Mayhem in Marquette (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Hi I''m Zak, what''s your name? Do you want a beer? Do you want a cigarette?', 7, 3, 'Terror at the Toy Shop');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel intense anger towards Billy, stay back!', 15, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Don''t let Aaron out of the basement until I say so!', 11, 0, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I just saw Aaron and I wanted to kill him.', 11, 0, 'Poveglia Island');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m having a little bit of residual feelings.', 15, 2, 'The Great Saltair Curse');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('As I look down the stairs I see Aaron, but it does not look like Aaron or feel like Aaron. He is unrecognizable.', 11, 0, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m not gonna talk to you about what kinda cars I have or what''s in my refrigerator.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Feel this! It''s freezing right over here!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I love devirginizing places.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m feeling so emotional at the moment. I just wanna cry!', 15, 2, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I decided that I''m gonna lock Aaron in here alone.', 11, 0, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('That''s a class-A EVP right there!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''ve got goosebumps on my arm, FEEL!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel like a spiritual fishing lure that is getting bites from the mean barracuda.', 15, 2, 'Letchworth Village');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('BRO! A mass of static energy just shot through my body!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I can''t give you an explanation... [of the pronunciation of "mercury".](https://www.youtube.com/watch?v=mjhBo0u6-wU)', 2, 4, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('That''s exactly what she said.', 7, 3, 'Petrified in Pahrump');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It''s pitch darkness.', 7, 3, 'The Great Saltair Curse');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There is no relaxation.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Do these people know they''re being sandwiched between 2 layers of demonic energy?', 7, 3, 'Kell''s Irish Pub Restaurant');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('His heart was stolen. Not by a girl, his physical heart.', 7, 3, 'Hellfire Caves');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You know who has experience in guys beds? Nick Groff.', 7, 3, 'Olde Fort Erie');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Ultraviolet lights are purple, because they are that color.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Are you making me angry? Are you giving me aggression?', 7, 3, 'The Great Saltair Curse');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('When we create emotions it''s kind of like we''re sweating, and what comes off of our skin is like energy.', 7, 3, 'Former Psychiatric Hospital');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I lost my breath. I got really lightheaded right here.', 7, 3, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel like I have a weird connection to Mark Twain.', 7, 3, 'Territorial Enterprise');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('They''re pulling the heat from around me - the thermal heat energy.', 7, 3, 'Terror at the Toy Shop');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I just received a massive EMF spike.', 7, 3, 'Lost Souls of the Berkeley');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Do you want to come play with my balls?', 7, 3, 'Stone Lion Inn');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Dude! It''s supposed to be spelled as "sidjuation".', 9, 5, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('That was one of the most chilling EVPs we''ve ever captured.', 7, 3, 'Lost Souls of the Berkeley');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We want answers... [for the pronunciation of "mercury".](https://www.youtube.com/watch?v=mjhBo0u6-wU)', 2, 4, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is the actual bullet hole. Of the bullet.', 7, 3, 'Gettysburg');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Will I pass out on the floor and be trapped in another time, while doctors call it "a stroke"?', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I saw a dark mist with my own eyes!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m the official brothel inspector.', 7, 3, 'Apache Junction');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('As Billy feels a bad vibe, this anomaly shoots behind him.', 7, 3, 'Petrified in Pahrump');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There is not good vibes in here. At all.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Our credi-bili-ty, our reputation.', 7, 3, 'The show''s intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I can hear you mumbling and saying things that are annoying me.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron starts to leave us, and it makes me angry.', 10, 0, 'Petrified in Pahrump');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('*\* Unexplained noises \**', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('A light anomaly just shot into {author}''s head!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This costume shop just got a hell of a lot more [bleep] creepy.', 7, 3, 'Terror at the Toy Shop');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('That was the most romantic paranormal experience interview I''ve ever done.', 7, 3, 'Hellfire Caves');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is the first time I''ve ever heard of a West African Nail Fetish Hate God!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron "voluntarily" goes into the closet.', 10, 0, 'Old Bullion Plaza School');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('A ball of light just shot into {author}''s chest!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('What are we feeling? You know that we''re feeling you.', 7, 3, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We could not debunk this as being some kind of insect.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You really don''t understand what I experienced when I held that foot in my hand.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('In the dream, I killed people knowing that it wasn''t morally wrong.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I am hot, but right now, my legs are chilling up.', 6, 3, 'LA Police Station Invasion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('*{ DEBUNKED }*', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('THERE''S A TEENY TINY FIGURE ON MY RECORDER!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You in there? Let''s go. Come out of your clothes. Come in here.', 7, 3, 'LA Police Station Invasion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m a funny guy, you know? I like to laugh... play games... if that''s alright...', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Being scalded by that pot sticker has jolted my mind back to the task at hand.', 7, 3, 'Chinese Town of Locke');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You guys be careful because that could have been a little imp.', 7, 3, 'Crisis in Long Beach (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Well, I hate slavery.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I just felt something grab my ass... like, hard, Nick! Hard, I could feel like this on my-on my BUTT!', 7, 3, 'Gettysburg');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel like doing this whole Zoom call thing with Aaron was a bad idea.', 10, 0, 'Jacksonville Family Curse (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We don''t call this ghost hunting, even in jest.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Bro! Please correct your spelling of "sidjuation".', 9, 5, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron and I are white, but we''re not a threat to you.', 7, 3, 'Chinese Town of Locke');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is the part of the Astral plane that contains the most mystery.', 7, 3, 'Battle of Los Angeles');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''ve never never felt emotions.', 7, 3, 'Kentucky Slave House');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Just breathe deeply. Let your body become a part of the fabric of this location.', 7, 3, 'Montecito Mansion Of Mystery');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is one of the most intense experiences of my life.', 7, 3, 'LA Police Station Invasion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I will lock you in the basement alone if you misspell "sidjuation" again!', 9, 5, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We''re here, and yes, I am provoking.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We''re not here for beauty, we''re here for darkness.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It was a blight or right blight bright light white.', 7, 3, 'Emergency in Elk Grove');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I have hydrogen in my farts.', 7, 3, 'Apache Junction');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('What''s happening right now is very chilling.', 7, 3, 'Henderson Hell House');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This right here-water- is what killed all the people in Sacramento.', 7, 3, 'Sacramento Tunnels');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I just saw a dark shadow figure behind you!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('The one thing we don''t do is touch or cut my hair.', 7, 3, 'Fort Chaffee');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is why I wanted to send somebody in solo. We need to examine that lamp.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It just feels like these raindrops are the tears of the orphans that came here.', 7, 3, 'Twin Bridges Orphanage');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('{author} is mocking the Holy Trinity.', 31, 6, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Nobody''s perfect, unless you''re Paris Hilton - wait, she has gigantic clown feet.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('In The Matrix, Keanu Reeves is injected with new programs and he evolves with each new packet of knowledge. It''s the same for me.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There''s a heaviness in the air that begins to trigger something inside of me.', 7, 3, 'The Great Saltair Curse');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron can go from happy and laughing to Dark Aaron in a second. I call him The Complainer.', 10, 0, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('The Devil: just leave him alone.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I continue trying to communicate with this female, but she never speaks again.', 7, 3, 'Old Bullion Plaza School');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('As soon as I step foot in this room, I am overwhelmed by an aggressive energy that feels like it''s circling around me.', 7, 3, 'LA Police Station Invasion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Right now, the entire house is complete dark.', 7, 3, 'Montecito Mansion Of Mystery');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('A very negative spirit attachment followed me home and affected me for about 3 days. I can''t wait to come back and do it again.', 6, 3, 'Territorial Enterprise');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('All it takes is one push and you can critically injure me! Do it!!', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Ooh, I just got frozen!', 7, 3, 'Lost Souls of the Berkeley');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('For the investigation, we need to find women, put masks on them, and and, uhhhh, have us recreate these orgies.', 7, 3, 'Hellfire Caves');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Once again, I''m not feeling like myself.', 14, 2, 'Acadia Ranch Sanitorium');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Are you just pressing on my chest? Because you don''t want me up here, right? I don''t like that... Aaron, get up here.', 10, 0, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('And that''s what we do when we see evil -- run like hell.', 7, 3, 'Hill View Manor');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, because that spirit just called you by first and last name, I''m sending *you* there to investigate tonight.', 10, 0, 'Territorial Enterprise');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('At one point, Darren''s wife came back to the house with her pants unbuttoned and belt undone and said that Zozo had attacked her.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Capturing ground-breaking proof of the paranormal.', 7, 3, 'The show''s intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Are you here, little kid? Don''t be afraid.', 7, 3, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I never believed in ghosts until I came face-to-face with one.', 7, 3, 'The show''s old intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('The one thing we don''t do is bitch about things.', 7, 3, 'Fort Chaffee');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, will you take your shirts off so that we can see if it will scratch you on camera?', 10, 0, 'Mayhem in Marquette (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('In the middle of an interview, you never just get up, fart, or run away. As long as we get them things out of the way, we can continue, sir.', 7, 3, 'Letchworth Village');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I felt like I just got stung by a... a spider.', 7, 3, 'LA Police Station Invasion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, I want you to go into the ladies'' room.', 10, 0, 'Lost Souls of the Berkeley');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This house was calling to me for something, in some psychic way.', 7, 3, 'Montecito Mansion Of Mystery');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You wanna push me? Let me feel your touch!', 7, 3, 'The Great Saltair Curse');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I hear something move in the office. Then an energy shoots towards me.', 7, 3, 'Petrified in Pahrump');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('As I always say, these locations that we investigate, we don''t find them... they find us.', 7, 3, 'Mountain Oaks Mayhem');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We act goofy and strange sometimes, which the haters love. "Oh, there they go, possessed again," they say.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m NOT one of those goons with fame-injected egos who are cast in a show for a season or two and think they know everything about ghosts.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I knew I had done something bad and freaked out a little. I actually ran to the bathroom to look for the knife I had used to stab everyone to make it sure it was still there and not bloody.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''ve explored the worst holes on earth and found beauty and wonder in places most people find disgusting.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It''s like I''m trying to overdose on ghosts. I''m an addict.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('No, no, no! Stop! Stop it! I''m being serious.', 7, 3, 'Old Bullion Plaza School');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Ow, Billy, I''m getting that pricking feeling!', 14, 2, 'Nightmare at the Roxie');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We immediately go inside. And because Aaron is being affected, we follow his lead.', 11, 0, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('If I could say this humbly, but also confidently: we specialize in ghost communication.', 7, 3, 'Return to the Riviera');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('*... understand...*', 31, 7, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Are the ghosts mistaking Aaron''s digital recorder for a bomb!?', 7, 3, 'Kell''s Irish Pub Restaurant');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel an ice-cold pocket of air, as if something is manifesting!', 7, 3, 'Lost Souls of the Berkeley');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron has a strong feeling to go to the basement with the Polterpod.', 11, 0, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Are you eating a beef stick? In the midst of all of this you''re eating a beef stick?', 7, 3, 'Acadia Ranch Sanitorium');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This day and age makes me sick sometimes.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('{author} mentioned the number ''3''. They must be mocking the Trinity.', 30, 6, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel something inside my chest. It''s cold inside my rib cage.', 15, 2, 'Nightmare at the Roxie');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('ź̵̩͝o̷͇̱͒ź̶͉̺͔o̶͎̪̝̍ ̵̤̳̯̌̀z̴͈̈ȍ̶̧̻̈z̵̗̄͘͠o̸̻͉͑ ̵̪̖̊̉z̶̡͗̏ộ̷͙̚̕z̵̫̳̈́͑̋ǫ̸̤̬̕͘ ̶̮̮̉͒̄z̴̲̑̎o̶̪̍͛̚z̵̰̆õ̴͚̩̚ ̵͎̦͙̊̓z̷̫͍̾͆̊ọ̵̗̏͛z̷̨̬͂̂͘o̸̖̺̐̅̄ ̴̦̀͑̅z̶̤̾͆̿ò̵̺͖̂͘ẕ̵̨̀͘͜o̴̼̼̎ ̷̧̮̙͋̓z̶̝̺̩͛͗ò̶͔́z̷͎̅̌̅ͅo̷̢̜̓ ̶̹͌̐z̸͍̰̐̾͜ȍ̴͎͋z̶͚̙̿̎͆o̴̧̕ ̶͎̰̏̆̂z̵͓̟͚̐o̷̤̼̾z̶̞͌̾͠ơ̸̠͎͇̑͐ ̶͔̹̏̈͆z̴̠͐̈́̕o̴͖̐͑͐z̷̟̃̿͜ò̵͍̤́ ̶̨̅̇͝ž̶̢̥͔̋̀o̷̪͒z̷̰̀ö̶̲͉̯́̌ ̷͓͎̝̋̈́z̶̨̯͙̑̀̂o̴̗͑͌z̷̼̋ȏ̵ͅ ̴̺̈z̸̢̠͛ô̷̤͝z̵̡͍̭̑̍́o̷̘͕͌ ̷̣̔̈́͑z̷͔̍o̷̟͝ź̵̮̽o̴̪͆̿ ̴̛̹̟͆̽z̸̗̏o̶̰̼̖͒͊z̵̘̰̯̆ŏ̸͔͎͌̕ ̶̫̫̰̔͗̀z̸̢͛̀̄o̸̧̝̐z̷̤̎͛̚o̴̻̒ ̴̭̯̀z̵̠̖̈́ͅǫ̸̜̅͂z̸̜̆́͝ŏ̷̼͕̇ ̴̡̝͕̏́͠z̸̪̀̈͠ò̵͕͖̹̉z̷̳̓͌̒o̵̙͆ ̴͎̩̩̚z̴͙͐͛ŏ̶͖͖̣z̸̝͓̎o̷͕͔̩͑ ̴͈̀̒̋ẑ̷͚͕͠ͅo̸͚̥̰̍z̵̹͐̇ô̷̦̋̎ ̵̨̭̭̌͘z̴̰̥̰̄ǫ̴̪̰̑̒̽z̶̹̎o̴̘͂͝ ̷̅̂̒͜z̸̨̰̕ō̷̩̋͗z̵̟͗o̶̯̐ ̶̖̜͐̇z̵̡̛̛̞͊õ̷͙̗̽z̸̬̠̜̀̕͠o̴̹̍̓ ̶̟̈̌͘ź̴̙͝o̸̳͆z̴̲̾̽o̵̳̘͋͝ ̸͇̿̌z̷̛͙o̶͓͑̕ẕ̴̄̀o̴͙̝̿̕ ̷̜͘z̴̙̟̎̅o̴̢̲͐͝z̴̧͋͊ǫ̷̨͎̀ ̷̹̪̪̈́z̶̗̔͠͝o̴̪͝z̶͚̤̰̾o̸̧̍ͅ ̴̰̳͓̓̈́ź̴̘͓̭̎̀o̴̞͈̾͝z̵̖̈́͒o̷̲̪̎̍͝ ̶̡̒̌ͅz̸̧̹̪͝ǒ̷̢͚̌͠z̷̫̟͈̎͐o̵͇͈̟͆̚͠ ̵͙̑̚̚ź̵͕̲͐̐ó̸̧̮̥̋z̷̖̒͊o̷̦̽̍͜ ̸̲̃z̵̙̯̺͌̑ö̵̫́͌̌ͅz̷̡̹̜͑̔ô̷̙͌̍ ̸̢͉̩̂z̴͈̓o̷͎̜͎̎̽̉z̸͍̍ô̵̫͓̈́ ̶̥̝̽͑͛z̷̻͈͘͠o̸̤̓̈́z̵̼͉̰̊́̃ō̷̫̳̿͆ ̴̦̼̀z̶̪͂̾͂ơ̶̥͚̊̑z̵̯̬̔̔ò̸̡̌ ̴̞͈̙͒̈́̋ẕ̶̪̀̈͌o̵̡̳̐̚͝z̷͖̩̥̚o̴̟̮͝ ̷͎̐z̶̩̅̔͋ö̷̖́ź̶̢͇̈́o̸̞͒̅ ̴͓̽̈̆ͅz̵̜͙̯̓ò̷̞́z̴̼̗͙͂o̸̩̲͍̍ ̸̣̖̈̌z̸̟͗̐o̷̡͒̊z̷͇̠͐̚ǫ̵͇̓ ̴̟̊̽͠z̵͇̝̉͠ͅȯ̷̲̗͂͂z̴̢͈̥̈̉̽o̵̲͎̒͠ ̸̯̣̰̇̕͝z̸͍͝ȍ̸̫͊ž̵͓͇̀̽ǒ̷̩͓̫̈́͒ ̷̟̂́̅z̶͔̀̚ö̸̃̏͜z̶͈̋o̴̬͒̽ ̵̪̮̓̃͐z̸͈͎͍̚o̴̥̣͐z̸̨̻̗̑̾o̴̹̟̍͗ ̶͈̈́z̸̳͐̀͂ö̴͕́̂z̵̨̨̎o̴̝͌ ̸̲͇̟̿̾̌ẑ̸̙͉̅o̴̳̰͛͝ẕ̵̹̭̚ô̴̺ ̷̜̋̈z̸̻̀ö̸̪͔́͗z̴̡̰͎̄̎o̷̲̻͛̆́ ̷̨̞̈́̚z̶̳̿̾õ̸̼͉z̶̲̈́̍o̸̮̮̹͊̽ ̸̥̰̂z̸̲̄̓̕ơ̵̡z̸̗̯͔̓̀̈́ò̸̩͍̙̾ ̵͕̮̯̔̿͗z̵̹͎̈́̊̏o̵͓͓͗ż̸̟̻͜͠ȍ̵͜ ̴̭͕̺͊͝z̶̰͚͓̀o̸͇͓͛͌z̸̫͗̓̎ó̸̤͈̥͝͝ ̸̹͙͛͆̇z̴̡̭͎̈́̋ọ̷̱̗͗z̸͎̗͎̓ó̶̬ ̴͛̇͜z̸̖͘o̶͍̅̋̑ͅz̴̘̘͆ȍ̴ͅ ̸̲̘͖͋͌z̵̹̭͕̋͆̓ỏ̸̢̟̭͝z̶͓͇̯̀̌o̶̭̯͒͝ ̷͚͉̭̈́͝z̵̠͈̀̌o̷̥͕̓͜͠z̶̢̫̣̀ǒ̴͜ ̶͖̅͛z̶͓̎̏o̶͕̾̚͠z̴͈͗̃o̶̮͆̂͝ ̶̦̒̄z̷̤̅o̸̮̊̽ẑ̶̡̳͈͑͘o̶͈͆͌̀ ̸̯̙̥͆͆̕z̶͎̬̲̓͝o̸̢͖̞̔z̸͎͔̮̏ò̴̹͉̔̔ ̵̼͊͝z̷̢̝͕̄͑̂ọ̶͑z̵͇̆̌ọ̵͆ ̶̱͚͓̓z̷̡̗̮͐́͠ơ̸͎̫̠̎z̴̳͊͗͝o̵̧̪̭̚͝ ̶͎̻͖̅z̶͓͇̊̅̋o̸̠͇̔z̶̬̈́o̸͖͖̗̽͑ ̴̯͖̠̄͑̚ź̵̼̪̔ó̸͉z̴̳͚̬̓̍̾ò̸̭ ̷̢͓̒̉̿z̴͚̘͙͝ô̷͙z̶͎̤͉̀̐o̵͙͈͆͋͝ ̴̥̾z̴̬̭͙̏̈̕ṓ̴͍͠z̵̘͂̽ͅo̶͚̅̓̕ ̸̧͈͌͆z̷̨̓̐͗ơ̴͈͎̂̆z̶̙̟̀o̵̫͛͆́ ̸̖̀̑̂', 14, 8, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We have worked years to build our credibility... our reputation...', 7, 3, 'The show''s intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('STOP! Stop running!', 7, 3, 'The show''s old intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is what it feels like to be in the civil war. That''s why we do this.', 7, 3, 'Gettysburg');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You''re mocking the Holy Trinity by saying the number ''3''.', 31, 6, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I want all of us to hum together, so we get in perfect synchronicity, and I want us to again, calibrate our energy.', 7, 3, 'Montecito Mansion Of Mystery');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I just felt wind.', 7, 3, 'Old Bullion Plaza School');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m feeling anger and rage because you can''t spell "sidjuation"!', 9, 5, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I decide to send Aaron in front of me, at which time I see a ball of light shoot right into his back.', 10, 0, 'Emergency in Elk Grove');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('z̸̋̏̅ͅõ̴̞̀̄z̵̨̀͛̀͝o̴̪̓ ̵͚̼̠̖̾̿͝i̶̡͕̎̌͂ș̵̲̂͒ ̵̞̤͊̈̚͜h̷̙͈͚̖͛̀̐e̵̻͉̔̇͝r̷̥̅e̷͉͑͌̌ ̷̗͖̜͐̀͂z̴̥̣̏̐͗͐ọ̴̚ź̸͇̬̈́͜o̸̢̥̓ ̵͙̯̲͖̊͒̏̏ï̸̻͠s̸͈͋͑̆ ̶̘̦̈́̏h̶̘̫̅̀͑̆ȅ̴̪͉͚̝ř̷̦̯̤̳̾̆ě̷͈͕̾ ̴̛̙̒z̴̛̜̑͂̉o̸͉̊̉̅͐z̷̢͐̿̂̏ȏ̶̧̔͒ ̴̡̭̈́͊͝ì̷̘͝ş̴̛͔͍̥͊̀͘ ̴̪̖͚̗̓̈́͝h̵̬͈̲̚͝e̶̮͉̞͊̾r̶̞̔e̴̛͔͂̆̑ ̷̪̱̳̌z̸̢͙͎̒́̿̚o̶̩̱̹͐͆̌z̶͚̖̅ͅȏ̸̥̻͉̞ ̶̬̜͐i̶̧͂̎͜s̸̠̩̔͐͐̓ ̵̪͔͙̈h̵͎͋̓e̴͉̬̖̚͝ŕ̶͕̂̈́̂e̴̲͋ ̸̡͖͈̪̄z̴̡̟̭̉̉o̴̪͓̩̾̓̾z̴̧̹̬̪̀͆̕͝o̷͇̐ͅ ̴͎̱͎̖͆͆̏̂í̷͍̱s̷̲͛̐͛͝ ̶̧̥̈̍̓́ḩ̷̛͙̯̏͝e̵̻̝̗̋͊͌̾r̸̨͓̒̒̀ḙ̵̙̣̈́̿́ ̴͈̭̘̈́z̵̛̦̊̍ô̴̪̖̬͜z̸͔̮̟̱̋o̸̜͓͇̚ ̵̣̰̒̕̕į̷̈́̊͠s̶̞̗̦̍̑ ̸̠̈́h̴͔͑e̷̝̘͌r̶͎͓̮̹̐͌ē̵͖̳͚ ̴̯͇̼̿̐́̔z̷̤̃͗͐̓ǒ̶̭͎̫̕͜z̸̭͉̣͝õ̴͎̱̠ ̴͍̤̺͉̌̍̈́̓ĭ̶̦̎͘s̴̲͆̆ ̴̡̖͒̌̕h̷̯̔ë̵̐͜r̶̨͚̯͕̋e̷̫͚̰̊̀ ̸̣̳̓̆̈́͐ͅ', 14, 8, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('RAW. EXTREME.', 7, 3, 'The show''s old intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I suddenly feel inexplicably exhausted, to the point that I can barely stand up.', 14, 2, 'Nightmare at the Roxie');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('🎶 I like to play with toys, I brought my boys 🎶 Aaron likes to play with toys, a lot 🎶 And so we''re gonna come up the stairs 🎶 And we want you to sing with us, ''cause we don''t like to ride the bus 🎶', 7, 3, 'Old Bullion Plaza School');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron, use extreme provocation.', 10, 0, 'Chaos in Emmaus (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It literally felt like we were in the video game "Doom".', 7, 3, 'Fort Chaffe');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We want answers... ^(answers)', 7, 3, 'The show''s intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Sometimes you go to someone''s house and you don''t know if there''s gonna be 10, 20, 40, 50 people at this party, or you''re gonna go there by yourself and talk to a bunch of walls.', 7, 3, 'Battle of Los Angeles');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We tried to summon Satan. We tried to call him out. I hate to admit it, but we thought we could pull it off, and I witnessed one of the most disturbing things I''ve ever seen.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('She was crying because she''s been astral projecting herself and having a sexual relationship with me in the astral plane for a long time.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This is our evidence, our Ghost Adventures.', 7, 3, 'The show''s intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Tell Aaron to use provocation, since he''s feeling rage.', 10, 0, 'Jacksonville Family Curse (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Sometimes we have feelings and we can''t ignore them.', 7, 3, 'Riddle House');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Ghost Adventures is a serene island in an ocean of chaos.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('As Aaron asks "Why is he being affected", an unexplained light anomaly shoots directly into him.', 10, 0, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We have created like an electromagnetic roadway for any of these entities that are listening to me now.', 7, 3, 'Crisis in Long Beach (House Calls)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Don''t mention z̵̧̠̖̹̱̠̤̖̲̜͒͗̀̈́̍̏́̆͒͌͛͠o̸̧̡̡͚̰̙̘͚̥̝͑͐͗͠͝z̵̹͍̣͓̰̩͕̰̫̘͇͙̎́͗͌̈͑̀́̀͑̀ǫ̴͉̱͕̰͕́̓̚''̵̢̨̜̻̙̙̟̼͊̈́̄̏̃̒̅͑̀̋͘ͅš̶̩̥̓͗̿́̋̆͂͘͘ ̴̟̲̳̰̫̹̣͍̣͉͐n̵̛͉͍̯̔̐̌̅̿́̓̇̅͜å̶̢̡̰̱͓̭̝͂͛̆͗́̅́͊͜͠͠m̴̭͈͙̒̿ę̸̫̺̦͎̗̺̯̤̅͂͌.̴̝̃͝', 14, 8, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We won''t send a kid into space, but we''ll give him a portal to another dimension and invite a demon in.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Something led me, personally, to this building. It called out, and I answered its call.', 6, 3, 'Montecito Mansion Of Mystery');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You have reached your final destination. *Hell.*', 7, 3, 'Poveglia Island');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Jay is like Alex Trebek on Speed.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This makes me angry against the Spanish.', 7, 3, 'Castillo De San Marcos');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('At this moment, one of our X-cams in the men''s bathroom captures something compelling.', 7, 3, 'Nightmare at the Roxie');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It''s not me. I wear deodorant. I do not have B.O.', 7, 3, 'Apache Junction');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Ouch! I got a pain on the left side of my head.', 7, 3, 'The Great Saltair Curse');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('The guy is connecting with me, wants my energy. He knows that, like, I''m alpha, and he wants to use my power.', 7, 3, 'Acadia Ranch Sanitorium');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Every time I fly I have to pee. A lot. And I get scared I''ll get sucked out of the airplane lavatory with my wiener hanging out. But I have not, and will never take, a dump in an airplane.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There are things in this world we will never fully understand... ^(understand)', 7, 3, 'The show''s intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('This place is a ghost town, and a ghost town is this place.', 6, 3, 'Vulture Mine');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Just as Aaron discovers this creepy room, a voice tells him to be careful.', 10, 0, 'Whitmore Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Was this spirit being a smart ass?', 7, 3, 'Twin Bridges Orphanage');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m a sensitive. I feel emotions, and sometimes, people just don''t understand that.', 7, 3, 'Hotel Barclay');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Suddenly, I am overcome with fear and sadness.', 7, 3, 'Old Bullion Plaza School');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('z̵̦͌̄o̷͉̻̽̽͗ͅz̷̮̖͗o̶͔͎̱͑͘ ̶̢̩͌̊̀f̷̫̏͋̚o̴̺̒͂̎u̷̖̠̎̐ň̵͕̆d̶̟̎̀̌ ̷̛̙̏u̷̹̣̭̔̏s̵̗̾ ̴̼͉͑̀͊z̸͎̿̐ͅo̸̲̝͍̚z̶̯̖͓̀̌̀ō̵̖̬̃̒ ̶͔̮͈̂f̸̱͇̀̒͘o̵͉̞̗͋u̸̬̓ṅ̴͚̻̑̾ḓ̸̑̓ ̵̣͛ǔ̵͉̩̞s̴̗͔͉̆ ̸̡̳̿͒̂z̶̠̭̐ö̵̦̱́͘̕z̸̞̫̖̃͌͋ő̶̼̫̞͐͘ ̷̍̀͗ͅf̵̘͔͂ȏ̸͚̘͑̋u̷̝̓n̷̢̛̫͑̆͜d̷̰͔̏ ̵̱͍̫̆ú̶̧̥̼̔͝s̷̞̖̐̕ͅ ̶̼̾͋z̶̢̈ó̴̤̫z̴̳̞̊̓õ̵͈͓ ̴̹̲̊̑f̸̪̔̈́o̴͎͊́ů̷͔͇̥͝ņ̶͈̋̈́͝ḑ̴̯̟̓̀̔ ̸͖̩͆ủ̸͙̕s̷̤̄ ̴̢̤̈́̂̿z̶̻̘͑õ̷͇͎̩z̴̳̗̿̑ỏ̸̜͔̅ ̷̨̘̈͘f̴̙̭͛̇o̷̬̘͎͑̄ư̷̰͙̗̍n̴̰͋̇̽d̵̮͈̱͊ ̵͍̋ų̴̳̳͂s̵͙̓̎͊ ̴͍̯̯̈̌', 13, 8, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You wanted us; you got us!', 7, 3, 'The show''s old intro');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Not only did we come back, but we came... with a female!', 7, 3, 'Ohio State Reformatory');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We are dealing with a very strong place.', 7, 3, 'Fear in Flagstaff');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Bro, I just got energy out of nowhere. I''m just like ice-cold. Are you guys cold? Is it cold in here? ', 7, 3, 'Lockdown in Lancaster');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Can you please come hold my hand?', 7, 3, 'Fear in Flagstaff');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('At some point Aaron and I started calling each other G and talking in a slur for no reason.', 10, 0, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''ve had a foot fetish since I was a little kid. It''s no secret. I like the cute little toes when they look like soldiers all lined up. Do you know what I mean? I''m not weird. I''m not like a WEIRD foot fetish guy.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('How many times will Aaron fart on live TV? How will I edit that out?', 10, 0, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It feels like we''re walking into a room on another planet.', 14, 2, 'Lockdown in Lancaster');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I felt nirvana. I felt ecstasy. I felt an escape from everything. I felt so great. I felt like I wanted to have sex.', 14, 2, 'Fear in Flagstaff');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Its 4:17 in the morning, I''m in the basement, and things are about to get weird.', 7, 3, 'Houghton Mansion');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I''m sending Aaron in alone to investigate.', 10, 0, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('You guys are just a bunch of evil cowards; that''s what you guys are.', 7, 3, 'Bobby Mackey’s Music World');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I question God and Jesus, but I don''t question exorcists.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We will put ourselves on the line to answer anybody''s call for help.', 7, 3, 'Emergency in Elk Grove');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('We swim in the spiritual ocean while everyone else is snorkeling.', 7, 3, 'I am Haunted: Living Life Through the Dead (Book)');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Aaron''s deeply condescending response is proof that we''re not in a balanced state of mind.', 11, 0, 'Los Feliz Murder House Part 1');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('There was murders, there was mayhem, and all of this has settled down to the bottom like gold in a gold pan, and it''s just waiting down there. That''s where the secrets are kept.', 7, 3, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('*... answers...*', 36, 1, null);
INSERT INTO public.phrase (content, usages, type, source) VALUES ('It''s like we have stepped into a very dark world, and all of us are feeling it.', 15, 2, 'Lockdown in Lancaster');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('The moment Aaron opens the door, a putrid odor fills the hallway.', 10, 0, 'Hotel San Carlos');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I just feel like I shouldn''t have asked to go to the sixth dimension.', 14, 2, 'King Gillette Ranch');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Without warning, I''m overcome with a sense of dread.', 6, 3, 'Village of Lost Souls');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I know I''ve been a little insecure about the dad bod.', 6, 3, 'The Beast of West Hills');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('I feel as though we are diving dangerously deep into the chaotic spiritual dimension on this island.', 14, 2, 'Devil Island');
INSERT INTO public.phrase (content, usages, type, source) VALUES ('Now, the female comes through and tells me I''m awesome.', 6, 3, 'Devil Island');
